事業の実装
kaji-ryuya/mokumoku pull request #2
Opened 2023-05-23 14:42 UTC by kaji-ryuya

suggestion branchで提案した、事業の実装。

2023-05-23 14:44 UTC, kaji-ryuya commented
suggestion branchでいただいたspecフォルダですが、もともとmokumokuアプリに入っていたものと同じようです。
お手数おかけいたしますが、ご確認をお願いいたします。

2023-05-25 06:51 UTC, Tsuchiya2 commented
https://github.com/kaji-ryuya/mokumoku リモートリポジトリのdevelopブランチを拝見しましたが、①時に共有しているspecフォルダが無いのを確認しました。何を確認すれば良いのでしょうか。

https://github.com/kaji-ryuya/mokumoku/tree/develop/spec を拝見しまして、そこには`woman_only_events_spec.rb`なども無いようなのですが...。（認識が異なっていたらすみません。一旦ご確認をお願いいたします）

2023-05-25 08:29 UTC, kaji-ryuya commented
私の確認不足でした。
置き換えたものと思っていたのですが、実際には置き換わっていなかったようです。
申し訳ございませんでした。

2023-05-25 10:31 UTC, kaji-ryuya commented
事業の実装をいたしました。ご確認をお願いいたします。
![image](https://github.com/kaji-ryuya/mokumoku/assets/114638792/b96a3a85-dad5-4fd1-8462-c6b266f3b46e)

2023-05-25 10:45 UTC, busitora requested changes
コメントしました！

2023-05-25 10:45 UTC, busitora commented on app/views/events/show.html.erb
> +            <% if @event.only_woman == "true" %>
```suggestion
            <% if @event.only_woman? %>
```
がいいですね

2023-05-25 17:04 UTC, kaji-ryuya commented
レビューありがとうございます！
ご指摘箇所の修正をいたしました。
条件まわりスッキリしました！ありがとうございます！
その他のif条件も整理致しましたのでご確認をお願いいたします。

2023-05-26 11:33 UTC, takyyk commented
@kaji-ryuya 
LGTMです！！

2023-05-26 11:35 UTC, kaji-ryuya commented
LGTMありがとうございます！

2023-05-26 11:35 UTC, merged